import{K as S,a as $,e as O,$ as q,c as C,l as h,g as b,u as F,h as u,M as I,Q as w,S as y,q as K,_ as M,b as p,x as _,B as j}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.15.1.js";import{O as A}from"./khao-ui-svelte-this-4.15.1.js";import{Q as D}from"./khao-ui-button-4.15.1.js";import"./khao-ui-icon-4.15.1.js";const G=(o,t)=>{const i=a=>{a.forEach(n=>{n.isIntersecting&&t&&t()})},s={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(i,s).observe(o)},x=["1"],H=(o,t,i)=>{const s=document.location.href;let a="1",n="2",l=`${s}${t}${n}`;if(s.includes(t)){const r=s.split(t);r.length===2&&(a=r[1].replace("/",""),n=`${parseInt(a,10)+1}`,l=s.replace(`/${a}`,`/${n}`))}x.indexOf(n)===-1?(fetch(l).then(r=>{if(!r.ok)throw new Error(`error loading next page ${l} , perhaps we have reached the end!`);return r.text()}).then(r=>{const c=document.querySelector(`${o}:last-of-type`);var d=document.createElement("template");d.innerHTML=r,d.content.querySelectorAll(o).forEach(g=>{var f;(f=c==null?void 0:c.parentElement)==null||f.appendChild(g)}),i!==void 0&&i(),history.pushState({},"",l)}).catch(r=>{console.log(r)}),x.push(n)):console.log("already added",n)};var N=S('<div class="spinner svelte-wcxk2y"></div>');const R={hash:"svelte-wcxk2y",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-wcxk2y {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-wcxk2y-rotation 1s linear infinite;}

  @keyframes svelte-wcxk2y-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function E(o){O(o,R);var t=N();q(o,t)}customElements.define("khao-spinner",$(E,{},[],[],!0));var T=S('<div class="infinite-scroll svelte-14hyps5"><!> <!></div>');const V={hash:"svelte-14hyps5",code:".infinite-scroll.svelte-14hyps5 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function J(o,t){C(t,!0),O(o,V);let i=h(t,"querySelector",7),s=h(t,"paginationSlug",7),a=h(t,"buttonLabel",7),n=h(t,"numberOfPages",7,"1"),l=h(t,"showButtonOnFirstLoad",7,"true"),r=b(!1),c=b(!1),d=b(1);const g=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),f=()=>{y(d)<parseInt(n(),10)&&u(r,!0)},L=()=>{H(i(),s(),B),u(r,!1),u(c,!0),j(d)},B=()=>{u(r,!1),u(c,!1),window.dispatchEvent(g)};let m;F(()=>{l()==="true"&&u(r,!0),G(m,f)});var v=T(),k=I(v);{var z=e=>{D(e,{get label(){return a()},onClick:L})};w(k,e=>{y(r)&&e(z)})}var P=K(k,2);{var Q=e=>{E(e)};w(P,e=>{y(c)&&e(Q)})}return _(v),A(v,e=>m=e,()=>m),q(o,v),M({get querySelector(){return i()},set querySelector(e){i(e),p()},get paginationSlug(){return s()},set paginationSlug(e){s(e),p()},get buttonLabel(){return a()},set buttonLabel(e){a(e),p()},get numberOfPages(){return n()},set numberOfPages(e="1"){n(e),p()},get showButtonOnFirstLoad(){return l()},set showButtonOnFirstLoad(e="true"){l(e),p()}})}customElements.define("khao-infinite-scroll",$(J,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
