import{r as x,h as S,o as E,m as O,q as F,c as h,w as b,u as K,j as c,W,K as j,a as M,Y as m,d as w,B as T,V}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.17.8.js";import{W as y,b as Y}from"./khao-ui-svelte-this-4.17.8.js";import{T as A}from"./khao-ui-button-4.17.8.js";import"./khao-ui-icon-4.17.8.js";import"./khao-ui-svelte-style-4.17.8.js";const D=(n,t)=>{const i=a=>{a.forEach(o=>{o.isIntersecting&&t&&t()})},s={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(i,s).observe(n)},k=["1"],G=(n,t,i)=>{const s=document.location.href;let a="1",o="2",l=`${s}${t}${o}`;if(s.includes(t)){const r=s.split(t);r.length===2&&(a=r[1].replace("/",""),o=`${parseInt(a,10)+1}`,l=s.replace(`/${a}`,`/${o}`))}k.indexOf(o)===-1?(fetch(l).then(r=>{if(!r.ok)throw new Error(`error loading next page ${l} , perhaps we have reached the end!`);return r.text()}).then(r=>{const u=document.querySelector(`${n}:last-of-type`);var d=document.createElement("template");d.innerHTML=r,d.content.querySelectorAll(n).forEach(v=>{var p;(p=u==null?void 0:u.parentElement)==null||p.appendChild(v)}),i!==void 0&&i(),history.pushState({},"",l)}).catch(r=>{console.log(r)}),k.push(o)):console.log("already added",o)};var H=x('<div class="spinner svelte-qlm6m4"></div>');const J={hash:"svelte-qlm6m4",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-qlm6m4 {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-qlm6m4-rotation 1s linear infinite;}

  @keyframes svelte-qlm6m4-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function L(n){E(n,J);var t=H();O(n,t)}customElements.define("khao-spinner",S(L,{},[],[],!0));var N=x('<div class="infinite-scroll svelte-wtq3d0"><!> <!></div>');const Q={hash:"svelte-wtq3d0",code:".infinite-scroll.svelte-wtq3d0 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function R(n,t){F(t,!0),E(n,Q);let i=h(t,"querySelector",7),s=h(t,"paginationSlug",7),a=h(t,"buttonLabel",7),o=h(t,"numberOfPages",7,"1"),l=h(t,"showButtonOnFirstLoad",7,"true"),r=b(!1),u=b(!1),d=b(1);const v=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),p=()=>{w(d)<parseInt(o(),10)&&c(r,!0)},$=()=>{G(i(),s(),B),c(r,!1),c(u,!0),V(d)},B=()=>{c(r,!1),c(u,!1),window.dispatchEvent(v)};let g;K(()=>{l()==="true"&&c(r,!0),D(g,p)});var z={get querySelector(){return i()},set querySelector(e){i(e),m()},get paginationSlug(){return s()},set paginationSlug(e){s(e),m()},get buttonLabel(){return a()},set buttonLabel(e){a(e),m()},get numberOfPages(){return o()},set numberOfPages(e="1"){o(e),m()},get showButtonOnFirstLoad(){return l()},set showButtonOnFirstLoad(e="true"){l(e),m()}},f=N(),q=W(f);{var I=e=>{A(e,{get label(){return a()},onClick:$})};y(q,e=>{w(r)&&e(I)})}var P=j(q,2);{var C=e=>{L(e)};y(P,e=>{w(u)&&e(C)})}return T(f),Y(f,e=>g=e,()=>g),O(n,f),M(z)}customElements.define("khao-infinite-scroll",S(R,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
