import{Z as E,u as O,n as $,y as q,h as M,i as w,Y as P,a as p,l as C,q as H,e as L,H as T,L as Y,$ as Z,D as l,b as m,c as v,M as j}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.8.5.js";import{T as A}from"./khao-ui-button-4.8.5.js";import"./khao-ui-icon-4.8.5.js";import"./khao-ui-svelte-style-4.8.5.js";const D=(r,t)=>{const s=i=>{i.forEach(a=>{a.isIntersecting&&t&&t()})},o={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(s,o).observe(r)},S=["1"],G=(r,t,s)=>{const o=document.location.href;let i="1",a="2",c=`${o}${t}${a}`;if(o.includes(t)){const n=o.split(t);n.length===2&&(i=n[1].replace("/",""),a=`${parseInt(i,10)+1}`,c=o.replace(`/${i}`,`/${a}`))}S.indexOf(a)===-1?(fetch(c).then(n=>{if(!n.ok)throw new Error(`error loading next page ${c} , perhaps we have reached the end!`);return n.text()}).then(n=>{const g=document.querySelector(`${r}:last-of-type`);var u=document.createElement("template");u.innerHTML=n,u.content.querySelectorAll(r).forEach(d=>{var h;(h=g==null?void 0:g.parentElement)==null||h.appendChild(d)}),s!==void 0&&s(),history.pushState({},"",c)}).catch(n=>{console.log(n)}),S.push(a)):console.log("already added",a)};var J=E('<div class="spinner svelte-wcxk2y"></div>');const K={hash:"svelte-wcxk2y",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-wcxk2y {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-wcxk2y-rotation 1s linear infinite;}

  @keyframes svelte-wcxk2y-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function z(r){$(r,K);var t=J();q(r,t)}customElements.define("khao-spinner",O(z,{},[],[],!0));var N=E('<div class="infinite-scroll svelte-14hyps5"><!> <!></div>');const Q={hash:"svelte-14hyps5",code:".infinite-scroll.svelte-14hyps5 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function R(r,t){M(t,!1),$(r,Q);let s=w(!1),o=w(!1),i=1;const a=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),c=()=>{i<parseInt(y(),10)&&l(s,!0)},n=()=>{G(d(),h(),g),l(s,!1),l(o,!0),i++},g=()=>{l(s,!1),l(o,!1),window.dispatchEvent(a)};let u=w();P(()=>{k()==="true"&&l(s,!0),D(m(u),c)});let d=p(t,"querySelector",12),h=p(t,"paginationSlug",12),b=p(t,"buttonLabel",12),y=p(t,"numberOfPages",12,"1"),k=p(t,"showButtonOnFirstLoad",12,"true");C();var f=N(),x=H(f);{var B=e=>{A(e,{get label(){return b()},onClick:n})};L(x,e=>{m(s)&&e(B)})}var F=T(x,2);{var I=e=>{z(e)};L(F,e=>{m(o)&&e(I)})}return j(f),Y(f,e=>l(u,e),()=>m(u)),q(r,f),Z({get querySelector(){return d()},set querySelector(e){d(e),v()},get paginationSlug(){return h()},set paginationSlug(e){h(e),v()},get buttonLabel(){return b()},set buttonLabel(e){b(e),v()},get numberOfPages(){return y()},set numberOfPages(e){y(e),v()},get showButtonOnFirstLoad(){return k()},set showButtonOnFirstLoad(e){k(e),v()}})}customElements.define("khao-infinite-scroll",O(R,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
