import{Z as E,o as L,n as $,y as q,h as M,f as w,Y as P,u as p,D as l,E as m,l as C,q as H,e as O,H as T,$ as Y,O as Z,c as f,M as j}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.14.0.js";import{T as A}from"./khao-ui-button-4.14.0.js";import"./khao-ui-icon-4.14.0.js";import"./khao-ui-svelte-style-4.14.0.js";const D=(r,t)=>{const s=i=>{i.forEach(a=>{a.isIntersecting&&t&&t()})},o={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(s,o).observe(r)},S=["1"],G=(r,t,s)=>{const o=document.location.href;let i="1",a="2",c=`${o}${t}${a}`;if(o.includes(t)){const n=o.split(t);n.length===2&&(i=n[1].replace("/",""),a=`${parseInt(i,10)+1}`,c=o.replace(`/${i}`,`/${a}`))}S.indexOf(a)===-1?(fetch(c).then(n=>{if(!n.ok)throw new Error(`error loading next page ${c} , perhaps we have reached the end!`);return n.text()}).then(n=>{const v=document.querySelector(`${r}:last-of-type`);var u=document.createElement("template");u.innerHTML=n,u.content.querySelectorAll(r).forEach(d=>{var h;(h=v==null?void 0:v.parentElement)==null||h.appendChild(d)}),s!==void 0&&s(),history.pushState({},"",c)}).catch(n=>{console.log(n)}),S.push(a)):console.log("already added",a)};var J=E('<div class="spinner svelte-wcxk2y"></div>');const K={hash:"svelte-wcxk2y",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-wcxk2y {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-wcxk2y-rotation 1s linear infinite;}

  @keyframes svelte-wcxk2y-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function z(r){$(r,K);var t=J();q(r,t)}customElements.define("khao-spinner",L(z,{},[],[],!0));var N=E('<div class="infinite-scroll svelte-14hyps5"><!> <!></div>');const Q={hash:"svelte-14hyps5",code:".infinite-scroll.svelte-14hyps5 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function R(r,t){M(t,!1),$(r,Q);let s=w(!1),o=w(!1),i=1;const a=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),c=()=>{i<parseInt(y(),10)&&l(s,!0)},n=()=>{G(d(),h(),v),l(s,!1),l(o,!0),i++},v=()=>{l(s,!1),l(o,!1),window.dispatchEvent(a)};let u=w();P(()=>{k()==="true"&&l(s,!0),D(m(u),c)});let d=p(t,"querySelector",12),h=p(t,"paginationSlug",12),b=p(t,"buttonLabel",12),y=p(t,"numberOfPages",12,"1"),k=p(t,"showButtonOnFirstLoad",12,"true");C();var g=N(),x=H(g);{var B=e=>{A(e,{get label(){return b()},onClick:n})};O(x,e=>{m(s)&&e(B)})}var F=T(x,2);{var I=e=>{z(e)};O(F,e=>{m(o)&&e(I)})}return j(g),Z(g,e=>l(u,e),()=>m(u)),q(r,g),Y({get querySelector(){return d()},set querySelector(e){d(e),f()},get paginationSlug(){return h()},set paginationSlug(e){h(e),f()},get buttonLabel(){return b()},set buttonLabel(e){b(e),f()},get numberOfPages(){return y()},set numberOfPages(e){y(e),f()},get showButtonOnFirstLoad(){return k()},set showButtonOnFirstLoad(e){k(e),f()}})}customElements.define("khao-infinite-scroll",L(R,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
