import{H as O,X as S,J as L,f as $,r as F,z as h,c as b,Z as I,d as u,O as N,G as w,a as y,k as G,s as H,t as p,N as J,L as Q}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.16.0.js";import{x as K}from"./khao-ui-svelte-this-4.16.0.js";import{Q as M}from"./khao-ui-button-4.16.0.js";import"./khao-ui-icon-4.16.0.js";import"./khao-ui-svelte-style-4.16.0.js";const X=(o,t)=>{const i=a=>{a.forEach(n=>{n.isIntersecting&&t&&t()})},s={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(i,s).observe(o)},x=["1"],Z=(o,t,i)=>{const s=document.location.href;let a="1",n="2",l=`${s}${t}${n}`;if(s.includes(t)){const r=s.split(t);r.length===2&&(a=r[1].replace("/",""),n=`${parseInt(a,10)+1}`,l=s.replace(`/${a}`,`/${n}`))}x.indexOf(n)===-1?(fetch(l).then(r=>{if(!r.ok)throw new Error(`error loading next page ${l} , perhaps we have reached the end!`);return r.text()}).then(r=>{const c=document.querySelector(`${o}:last-of-type`);var d=document.createElement("template");d.innerHTML=r,d.content.querySelectorAll(o).forEach(m=>{var f;(f=c==null?void 0:c.parentElement)==null||f.appendChild(m)}),i!==void 0&&i(),history.pushState({},"",l)}).catch(r=>{console.log(r)}),x.push(n)):console.log("already added",n)};var j=O('<div class="spinner svelte-wcxk2y"></div>');const A={hash:"svelte-wcxk2y",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-wcxk2y {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-wcxk2y-rotation 1s linear infinite;}

  @keyframes svelte-wcxk2y-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function E(o){L(o,A);var t=j();$(o,t)}customElements.define("khao-spinner",S(E,{},[],[],!0));var D=O('<div class="infinite-scroll svelte-14hyps5"><!> <!></div>');const R={hash:"svelte-14hyps5",code:".infinite-scroll.svelte-14hyps5 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function T(o,t){F(t,!0),L(o,R);let i=h(t,"querySelector",7),s=h(t,"paginationSlug",7),a=h(t,"buttonLabel",7),n=h(t,"numberOfPages",7,"1"),l=h(t,"showButtonOnFirstLoad",7,"true"),r=b(!1),c=b(!1),d=b(1);const m=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),f=()=>{y(d)<parseInt(n(),10)&&u(r,!0)},q=()=>{Z(i(),s(),z),u(r,!1),u(c,!0),Q(d)},z=()=>{u(r,!1),u(c,!1),window.dispatchEvent(m)};let g;I(()=>{l()==="true"&&u(r,!0),X(g,f)});var v=D(),k=N(v);{var P=e=>{M(e,{get label(){return a()},onClick:q})};w(k,e=>{y(r)&&e(P)})}var B=G(k,2);{var C=e=>{E(e)};w(B,e=>{y(c)&&e(C)})}return J(v),K(v,e=>g=e,()=>g),$(o,v),H({get querySelector(){return i()},set querySelector(e){i(e),p()},get paginationSlug(){return s()},set paginationSlug(e){s(e),p()},get buttonLabel(){return a()},set buttonLabel(e){a(e),p()},get numberOfPages(){return n()},set numberOfPages(e="1"){n(e),p()},get showButtonOnFirstLoad(){return l()},set showButtonOnFirstLoad(e="true"){l(e),p()}})}customElements.define("khao-infinite-scroll",S(T,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
