import{e as x,c as S,u as $,y as E,j as F,o as h,$ as b,l as j,d as c,W as H,a as w,K,q as U,U as p,b as y,H as V,V as M}from"./khao-ui-svelte-dispatchRemoteControlEvent-4.17.6.js";import{b as T}from"./khao-ui-svelte-this-4.17.6.js";import{T as W}from"./khao-ui-button-4.17.6.js";import"./khao-ui-icon-4.17.6.js";import"./khao-ui-svelte-style-4.17.6.js";const A=(n,t)=>{const i=a=>{a.forEach(o=>{o.isIntersecting&&t&&t()})},s={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(i,s).observe(n)},k=["1"],G=(n,t,i)=>{const s=document.location.href;let a="1",o="2",l=`${s}${t}${o}`;if(s.includes(t)){const r=s.split(t);r.length===2&&(a=r[1].replace("/",""),o=`${parseInt(a,10)+1}`,l=s.replace(`/${a}`,`/${o}`))}k.indexOf(o)===-1?(fetch(l).then(r=>{if(!r.ok)throw new Error(`error loading next page ${l} , perhaps we have reached the end!`);return r.text()}).then(r=>{const u=document.querySelector(`${n}:last-of-type`);var d=document.createElement("template");d.innerHTML=r,d.content.querySelectorAll(n).forEach(v=>{var m;(m=u==null?void 0:u.parentElement)==null||m.appendChild(v)}),i!==void 0&&i(),history.pushState({},"",l)}).catch(r=>{console.log(r)}),k.push(o)):console.log("already added",o)};var J=x('<div class="spinner svelte-qlm6m4"></div>');const N={hash:"svelte-qlm6m4",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-qlm6m4 {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-qlm6m4-rotation 1s linear infinite;}

  @keyframes svelte-qlm6m4-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function O(n){$(n,N);var t=J();E(n,t)}customElements.define("khao-spinner",S(O,{},[],[],!0));var Q=x('<div class="infinite-scroll svelte-wtq3d0"><!> <!></div>');const R={hash:"svelte-wtq3d0",code:".infinite-scroll.svelte-wtq3d0 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function D(n,t){F(t,!0),$(n,R);let i=h(t,"querySelector",7),s=h(t,"paginationSlug",7),a=h(t,"buttonLabel",7),o=h(t,"numberOfPages",7,"1"),l=h(t,"showButtonOnFirstLoad",7,"true"),r=b(!1),u=b(!1),d=b(1);const v=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),m=()=>{y(d)<parseInt(o(),10)&&c(r,!0)},L=()=>{G(i(),s(),z),c(r,!1),c(u,!0),M(d)},z=()=>{c(r,!1),c(u,!1),window.dispatchEvent(v)};let g;j(()=>{l()==="true"&&c(r,!0),A(g,m)});var I={get querySelector(){return i()},set querySelector(e){i(e),p()},get paginationSlug(){return s()},set paginationSlug(e){s(e),p()},get buttonLabel(){return a()},set buttonLabel(e){a(e),p()},get numberOfPages(){return o()},set numberOfPages(e="1"){o(e),p()},get showButtonOnFirstLoad(){return l()},set showButtonOnFirstLoad(e="true"){l(e),p()}},f=Q(),q=H(f);{var P=e=>{W(e,{get label(){return a()},onClick:L})};w(q,e=>{y(r)&&e(P)})}var B=K(q,2);{var C=e=>{O(e)};w(B,e=>{y(u)&&e(C)})}return V(f),T(f,e=>g=e,()=>g),E(n,f),U(I)}customElements.define("khao-infinite-scroll",S(D,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
