import{Y as O,J as L,h as E,l as q,e as K,c as k,K as p,S as P,N as T,n as C,d as l,x as g,X as m,T as J}from"./svelte-chunk-ekTI-Bhm.js";import{O as S}from"./svelte-chunk-D7ZEBFxW.js";import{r as N,x as M}from"./svelte-chunk-SdJWaq7a.js";import{x as X}from"./svelte-chunk-rsd-YvZ0.js";import{T as Y}from"./khao-ui-button-4.4.2.js";import"./khao-ui-icon-4.4.2.js";import"./svelte-chunk-Drg5G415.js";import"./svelte-chunk-i5w7oQmI.js";import"./svelte-chunk-yaEL7nV9.js";const j=(o,r)=>{const n=i=>{i.forEach(a=>{a.isIntersecting&&r&&r()})},s={root:document,rootMargin:"0px 0px 100px 0px",threshold:1};new IntersectionObserver(n,s).observe(o)},$=["1"],A=(o,r,n)=>{const s=document.location.href;let i="1",a="2",c=`${s}${r}${a}`;if(s.includes(r)){const t=s.split(r);t.length===2&&(i=t[1].replace("/",""),a=`${parseInt(i,10)+1}`,c=s.replace(`/${i}`,`/${a}`))}$.indexOf(a)===-1?(fetch(c).then(t=>{if(!t.ok)throw new Error(`error loading next page ${c} , perhaps we have reached the end!`);return t.text()}).then(t=>{const v=document.querySelector(`${o}:last-of-type`);var u=document.createElement("template");u.innerHTML=t,u.content.querySelectorAll(o).forEach(d=>{var h;(h=v==null?void 0:v.parentElement)==null||h.appendChild(d)}),n!==void 0&&n(),history.pushState({},"",c)}).catch(t=>{console.log(t)}),$.push(a)):console.log("already added",a)};var D=O('<div class="spinner svelte-wcxk2y"></div>');const G={hash:"svelte-wcxk2y",code:`:host {--khao-spinner-color: var(--khao-sys-color-neutral30);--khao-spinner-size: var(--khao-sys-size-regular-10);}.spinner.svelte-wcxk2y {width:var(--khao-spinner-size);height:var(--khao-spinner-size);border:5px solid var(--khao-spinner-color);border-bottom-color:transparent;border-radius:50%;display:inline-block;box-sizing:border-box;
    animation: svelte-wcxk2y-rotation 1s linear infinite;}

  @keyframes svelte-wcxk2y-rotation {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }`};function z(o){E(o,G);var r=D();q(o,r)}customElements.define("khao-spinner",L(z,{},[],[],!0));var H=O('<div class="infinite-scroll svelte-14hyps5"><!> <!></div>');const Q={hash:"svelte-14hyps5",code:".infinite-scroll.svelte-14hyps5 {display:flex;justify-content:space-around;width:100%;height:2rem;}"};function R(o,r){K(r,!1),E(o,Q);let n=k(!1),s=k(!1),i=1;const a=new CustomEvent("khao-infinite-scroll-loaded-more",{bubbles:!0}),c=()=>{i<parseInt(y(),10)&&l(n,!0)},t=()=>{A(d(),h(),v),l(n,!1),l(s,!0),i++},v=()=>{l(n,!1),l(s,!1),window.dispatchEvent(a)};let u=k();N(()=>{x()==="true"&&l(n,!0),j(g(u),c)});let d=p(r,"querySelector",12),h=p(r,"paginationSlug",12),b=p(r,"buttonLabel",12),y=p(r,"numberOfPages",12,"1"),x=p(r,"showButtonOnFirstLoad",12,"true");X();var f=H(),w=P(f);{var B=e=>{Y(e,{get label(){return b()},onClick:t})};S(w,e=>{g(n)&&e(B)})}var F=T(w,2);{var I=e=>{z(e)};S(F,e=>{g(s)&&e(I)})}return J(f),M(f,e=>l(u,e),()=>g(u)),q(o,f),C({get querySelector(){return d()},set querySelector(e){d(e),m()},get paginationSlug(){return h()},set paginationSlug(e){h(e),m()},get buttonLabel(){return b()},set buttonLabel(e){b(e),m()},get numberOfPages(){return y()},set numberOfPages(e){y(e),m()},get showButtonOnFirstLoad(){return x()},set showButtonOnFirstLoad(e){x(e),m()}})}customElements.define("khao-infinite-scroll",L(R,{querySelector:{},paginationSlug:{},buttonLabel:{},numberOfPages:{},showButtonOnFirstLoad:{}},[],[],!0));
